lambdas/agent-scaler/app.js
lib/argument-store.js
lib/aws-semaphore-agent-stack.js
packer/ansible/roles/agent/files/start-agent.sh
test/aws-semaphore-agent.test.js

- Adds a `SEMAPHORE_ENDPOINT` parameter which can be specified instead of `SEMAPHORE_ORGANIZATION`
- If set, the stack uses it without modification. If not, we assume the `SEMAPHORE_ORGANIZATION` specified is located at `semaphoreci.com`
- One of these needs to be specified. If none is, we error out.

Add SEMAPHORE_ENDPOINT parameter

---

.semaphore/semaphore.yml
lib/argument-store.js
lib/aws-semaphore-agent-stack.js
package-lock.json
package.json
test/aws-semaphore-agent.test.js

IAM role names can have up to [64 characters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#:~:text=A%20name%20for%20the%20IAM%20role%2C%20up%20to%2064%20characters%20in%20length), and if the stack name used leads to a name above that limit, CloudFormation truncates part of the stack name from the role name.
To address this, we reference the ARN for the instance role resource created by Cloudformation. Additionally, in order to make sure the same issue doesn't affect permissions related to the auto-scaling group name (255 characters maximum) and the SSM configuration parameter name (2048 characters maximum), we limit the `SEMAPHORE_AGENT_STACK_NAME` to 128 characters.

fix: use proper instance role arn

---

lib/argument-store.js
lib/aws-semaphore-agent-stack.js
test/aws-semaphore-agent.test.js

Currently, there's no way to add additional permissions to the instances that will run the agents. This PR introduces a new configuration parameter `SEMAPHORE_AGENT_MANAGED_POLICY_NAMES`, which takes a comma-separated list of managed policy names to attach to the instance profile role.

feat: allow custom policies to be attached to the instance profile role

---

packer/linux/ansible/roles/erlang/tasks/main.yml

If not specified, Erlang/OTP 25 is installed, which came out recently. The when CLI does not work with that version, so we pin the version of the Erlang runtime here.

fix: pin Erlang version

---

.gitignore
bin/aws-semaphore-agent.js
lambdas/ssh-keys-updater/app.js
lib/aws-semaphore-agent-stack.js
lib/dynamic-ssh-keys-updater.js
lib/github-keys.js
packer/linux/ansible/roles/agent/files/start-agent.sh
packer/windows/scripts/configure-github-ssh-keys.ps1
packer/windows/scripts/start-agent.ps1
test/aws-semaphore-agent.test.js

Currently, the way we provision the Github SSH public keys can lead to issues on agents that run in private subnets. [The Github API](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-personal-accounts) has a 60 requests per hour limit, which can be an issue if all the requests are being routed through a NAT gateway. So, we need a better way of handling those SSH keys.
This PR introduces a new SSM parameter to store the Github SSH keys. The parameter is initialized with the values from Github's API when bootstrapping/deploying the stack. To make sure we don't lead into rate limits for bootstrap/deploys as well, we cache the SSH keys in a local file for subsequent runs.
Another considerations:
- **SSM parameter size limitations**: standard SSM parameters have …

fix: store SSH keys in SSM parameter

---

lambdas/agent-scaler/app.js
lambdas/agent-scaler/package-lock.json
lambdas/agent-scaler/package.json
lib/aws-semaphore-agent-stack.js
test/aws-semaphore-agent.test.js

Currently, no metrics are published to CloudWatch, which makes it hard to monitor usage. This PR changes the scaler lambda to publish the occupancy for the stack to CloudWatch. The metric published is:
- Name: `JobCount`
- Dimensions (tags): the stack name and the job state (queued, running)

feat: publish occupancy metrics to CloudWatch

---

lib/argument-store.js
lib/aws-semaphore-agent-stack.js
test/aws-semaphore-agent.test.js

Currently, no ASG metrics are collected. This PR adds a new argument, `SEMAPHORE_AGENT_ASG_METRICS`, which receives a comma-separated list of ASG metrics to collect. The available metrics can be found [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.CfnAutoScalingGroup.MetricsCollectionProperty.html).

feat: add SEMAPHORE_AGENT_ASG_METRICS

---

lib/argument-store.js

Currently, the stack configuration can be provided either as a JSON file via SEMAPHORE_AGENT_STACK_CONFIG or as environment variables, but you can't combine the two. This changes it so that a user can provide a JSON file and then also provide environment variables. If there are duplicates, the environment variables take precedence. 
For my use case, I'd like to supply most of my parameters via the JSON file, but I'd also like to pass the `SEMAPHORE_AGENT_AMI` environment variable, so I don't have to store my AMI ID in source code.
I set the `SEMAPHORE_AGENT_AMI` and `SEMAPHORE_AGENT_STACK_CONFIG` environment variables then ran a CDK diff and saw:
```
Resources
└─ [~] ImageId (requires replacement)
├─ [-] ami-****
└─ [+] ami-****
```

allow overriding SEMAPHORE_AGENT_STACK_CONFIG values with env vars

---

lambdas/agent-scaler/app.js
package-lock.json
package.json

This PR updates the scaler lambda to use the new `/metrics` endpoint. The endpoint exposes the same numbers as the `/occupancy` endpoint + the number of agents per state:
```json
{
"jobs": {
"queued": 2,
"running": 8
},
"agents": {
"idle": 12,
"occupied": 4
}
}
```
A new `AgentCount` metric is pushed to CloudWatch, alongside the current `JobCount` one:
The `/occupancy` endpoint is now deprecated and will be removed in the future.

feat: use new /metrics endpoint

---

ci/delete-old-images.sh

Initially, this script was created to delete old private images. We don't manage public images, so it is only helpful to delete old AMIs. The only AMIs that are not deleted are the ones created for the latest tag.

fix: delete old AMIs based on tag

---

execution-policy.json
lib/aws-semaphore-agent-stack.js
test/aws-semaphore-agent.test.js

Launch configurations are an old thing, so they lack a lot of features. To support Mac, spot instances and possibly other things, we need to use launch templates.

feat: use launch templates

---

packer/windows/windows.pkr.hcl

The new AMIs released in 2022.12 use EC2 Launch [version 1.3.2003961](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-windows-ami-version-history.html). That version [has an issue that makes SysprepInstance.ps1 return a wrong exit code](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2launch-version-details.html). A new EC2 launch version `1.3.2003975` is already available, but the AMI provided by AWS was not yet upgraded. Until AWS provides updated AMIs, we'll use the previous one.

fix: use windows image from 2022.11

---

lib/aws-semaphore-agent-stack.js

This sets the `licenseConfigurationArn` field on the `LaunchTemplate` for macOS pools.
Prior to this change I was seeing the ASG fail to create with
```
AwsSemaphoreAgentStack/autoScalingGroup (autoScalingGroup) You must use a valid fully-formed launch template. One or more licenses need to be specified for a valid Server Manageability call.
```
Why the license config needs to be referenced by both the launch template and the host resource group is a mystery to me, but this works.

set licenseConfigurationArn on a LaunchTemplate for macOS

---

execution-policy.json

This adds a few new permissions to the execution policy. These permissions are not overly critical. 
* The delete permissions I ended up needing when failing to update stacks and rolling back. 
* The `autoscaling:CreateOrUpdateTags` was needed for tagging ASGs. 
* The removal of the `LaunchTemplateAccess` block was necessary because the policy hit the character limit when adding the other permissions. Conveniently, the permissions in the `LaunchTemplateAccess` block were replicated earlier in the policy: https://github.com/renderedtext/agent-aws-stack/blob/master/execution-policy.json#L18-L25.

add some permissions to the execution policy

---

packer/macos/files/terminate-instance.sh
packer/macos/macos.pkr.hcl
packer/macos/scripts/provision-ami.sh

Adds a shutdown hook to terminate the instance when the agent shuts down.
The shutdown hook is executed in a non-login shell. Since LaunchD has no default [environment generator](https://www.freedesktop.org/software/systemd/man/environment.d.html) mechanism like systemD, we'd need to use the `launchctl setenv` or `launchctl config` commands for configuring it.
Since the only environment setup needed in that script is to include `/usr/local/bin` to the `PATH`, we do it in the script itself, for simplicity.

fix: configure macOS shutdown hook

---

packer/macos/files/terminate-instance.sh

The AWS CLI is located in a different place in an ARM instance.

fix: shutdown hook for macOS ARM

---

lambdas/ssh-keys-updater/app.js

The SSH keys updater lambda doesn't currently log anything helpful about the HTTP response when GitHub gives us a non-successful one. This makes it difficult to troubleshoot issues.
This pull request fixes that by logging the complete HTTP response and headers when that happens.

fix: improve SSH keys updater logs on errors

---

lambdas/agent-scaler/app.js

Decrease the AWS API call timeouts to 1s. Also, use a `httpsAgent` on the `NodeHttpHandler` used, with a 1s timeout as well.

fix: decrease scaler lambda timeouts

---

lambdas/agent-scaler/app.js
package-lock.json
package.json

There's no need to fetch the agent token on each tick. Fetching it on the first one is enough. If the token changes, it will be re-fetch on the next lambda run.

fix: fetch agent token on first scaler lambda tick only

---

lambdas/agent-scaler/app.js

https://github.com/renderedtext/agent-aws-stack/pull/115 and https://github.com/renderedtext/agent-aws-stack/pull/117 solved the issue of the lambda timing out due to the SSM API being slow to respond. However, the lambda still seems to be timing out while running the last tick or because the check for stopping runs right before (milliseconds before) the 10s sleep. This pull request includes the next tick duration in the check too. That way, if the lambda doesn't have enough time for sleep + next tick (15s), we stop and let the next lambda run continue.

fix: include next tick duration on check

---

lib/dynamic-ssh-keys-updater.js
test/aws-semaphore-agent.test.js

The GitHub SSH keys are updated very infrequently, so there's no reason for us to check on them hourly. Daily seems like a better schedule for it.

fix: decrease SSH keys lambda rate

---

execution-policy.json

This adds the `lambda:DeleteFunctionConcurrency` and `lambda:ListTags` permissions to the execution policy. 
I tried to deploy my CDK stack update for 0.2.9 without including the changes to `exection-policy.json`. I ran into `is not authorized to perform: lambda:PutFunctionConcurrency on` during the CloudFormation stack update and subsequently `is not authorized to perform: lambda:DeleteFunctionConcurrency on` in the CloudFormation rollback. Obviously a miss on my part, but adding `lambda:DeleteFunctionConcurrency` will allow future rollbacks to work properly as necessary.
For the `lambda:ListTags`, I added this locally a while back, so I don't know the specific usage that requires it or what the error behavior is when this is missing. I am guessing it is used when deploying a Lambda with …

add lambda DeleteFunctionConcurrency and ListTags to execution policy

---

lib/aws-semaphore-agent-stack.js
test/aws-semaphore-agent.test.js

AWS provides a custom policy called [`CloudWatchAgentServerPolicy`](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/create-iam-roles-for-cloudwatch-agent.html), with the permissions needed for the CloudWatch agent. We should use the same permissions as that custom policy, which does not include the `logs:DeleteLogGroup` one.

fix: remove DeleteLogGroup permission from instance profile

---

package-lock.json
package.json
packer/macos/files/health-check.sh

Fixes a regression introduced by https://github.com/renderedtext/agent-aws-stack/pull/126. There's no proper way to shut down an instance running on top of a macOS dedicated host from the OS. So, we revert the health check script to use IMDS and the autoscaling API.

fix: use IMDS and autoscaling API on macOS health check

---

packer/windows/windows.pkr.hcl

The `Windows_Server-2019-English-Full-ContainersLatest` image has been removed due to its usage of the Docker EE runtime. We should use a base AMI with no container support for Windows, since that's the common use case.

fix: use EC2LaunchV2-Windows_Server-2019-English-Full-Base AMI

---

packer/linux/ubuntu-focal.pkr.hcl

The issue is related to https://github.com/hashicorp/packer-plugin-ansible/issues/69. We could [pin the plugin's version to v1.1.0](https://github.com/hashicorp/packer-plugin-ansible/issues/69#issuecomment-1631493391), but since we don't need to use a proxy adapter (our target has an IP), we'll use [use_proxy=false](https://developer.hashicorp.com/packer/plugins/provisioners/ansible/ansible#use_proxy) instead.

fix: do not use ansible proxy when provisioning linux

---

ci/agent-aws-stack-tester-permissions.json
package-lock.json
package.json

The AWS IAM permissions `s3:PutLifecycleConfiguration` and `ecr:PutLifecyclePolicy` are not required for `cdk bootstrap`.

fix: upgrade cdk libs to ^2.91.0

---

lib/aws-semaphore-agent-stack.js
lib/dynamic-ssh-keys-updater.js
test/aws-semaphore-agent.test.js

AWS [no longer supports Node 14.X](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-14-x-in-the-aws-sdk-for-javascript-v3/), so we need to use a newer version.

fix: do not use NODEJS_14_X lambda runtime

---

lambdas/az-rebalance-suspender/app.js
lambdas/ssh-keys-updater/app.js
lib/aws-semaphore-agent-stack.js
lib/dynamic-ssh-keys-updater.js
package-lock.json
package.json
test/aws-semaphore-agent.test.js

https://github.com/renderedtext/tasks/issues/6091
The node 16.x runtime will be [deprecated soon](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-supported), so we need to update to the node 18.x runtime. Since the 18.x runtime only has the [AWS SDK v3 available](https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/), the code was updated to use that SDK.

fix: update all lambdas to use node 18.x runtime

---

bin/aws-semaphore-agent.js
lib/github-keys.js
package-lock.json
package.json

https://github.com/renderedtext/tasks/issues/6192
We are shelling out and using curl to fetch the GitHub SSH keys needed to deploy the stack. That is not ideal since it does not allow us to see the error messages when that HTTP request fails. We should use the native node HTTP request library instead.

fix: do not shell-out for fetching GH SSH keys

---

execution-policy.json

We are currently in the process of replicating our agent pools to a different aws region to comply with certain failover requirements. In doing so, we needed to point to new vpc and subnet ids in our config files, but that resulted in this:
```
[Error at /AwsSemaphoreAgentStack] You are not authorized to perform this operation. User: <redacted> is not authorized to perform: ec2:DescribeVpnGateways because no identity-based policy allows the ec2:DescribeVpnGateways action
```
Going into the aws portal and manually adding this action to our policy allowed us to successfully deploy, so we would like this to be included in `execution-policy.json`

add DescribeVpnGateways action

---

bin/aws-semaphore-agent.js
lib/github-keys.js

This changes the GitHub SSH keys error handling logic when building the CDK objects to throw and catch a specific error rather than all errors. Previously, it caught all errors and then continued on. This meant that an error in a specific CDK object could cause an error and CDK would continue processing the stack. In my case, this meant that an incomplete set of objects were created resulting in a large change set and the deletion of most of the resources in my stack.
Tested manually:
```
> npm run deploy:ci
> aws-semaphore-agent@0.3.7 deploy:ci
> cdk deploy --require-approval never --progress events
==> No config file specified. Using environment variables ...
==> GitHub SSH keys found locally at '.gh_ssh_keys_1740499296', but expired. Fetching and storing at '.gh_ssh_keys_1740503496' …
```

fix GitHub SSH keys error handling

---

package-lock.json
package.json
packer/windows/scripts/start-agent.ps1

There's no need to restart agents now that we have a health check script running.
Ref: https://github.com/renderedtext/tasks/issues/7496

fix(windows): do not restart agent after a shutdown

---

lib/aws-semaphore-agent-stack.js
test/aws-semaphore-agent.test.js

This changes the Scaler lambda to use a different set of subnets depending upon the provided configuration:
* If `SEMAPHORE_AGENT_SUBNETS` and `SEMAPHORE_AGENT_VPC_ID` are set, then the given subnets will be used for the Scaler
* If `SEMAPHORE_AGENT_SUBNETS` is not set and `SEMAPHORE_AGENT_VPC_ID` is set, then the existing lookup will be used. The existing lookup tries to find a private subnet with egress to the internet.
This change is needed because the existing lookup didn't work for me when the private subnets were configured with an AWS network firewall sitting in between the private and public subnets:
```
Error: There are no 'Private' subnet groups in this VPC. Available types: Isolated,Deprecated_Isolated,Public
at LookedUpVpc.selectSubnetObjectsByType …
```

explicitly set scaler lambda subnets

---

lib/argument-store.js
lib/aws-semaphore-agent-stack.js

This adds a new `SEMAPHORE_AGENT_ALLOW_PUBLIC_SUBNET` parameter, which allows the Scaler lambda to run in a public subnet.
When a public subnet is provided and this setting is not enabled, the deploy shows:
```
Error: Lambda Functions in a public subnet can NOT access the internet. If you are aware of this limitation and would still like to place the function in a public subnet, set `allowPublicSubnet` to true
```
I started looking into adding a unit test for this, but there wasn't a clear and easy path since the `allowPublicSubnet` option doesn't actually change the CloudFormation template in any way. This setting is only a CDK construct. If you want I unit test for it, I can do so, but some substantial changes may be necessary.
I ran a manual deploy using this feature and it worked as …

allow public subnets for scaler lambda

---

lib/aws-semaphore-agent-stack.js
test/aws-semaphore-agent.test.js

The [AmazonEC2RoleforSSM](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonEC2RoleforSSM.html) managed policy is overly broad, it includes arbitrary read/write to any S3 bucket in the same AWS account:
```json
{
"Effect" : "Allow",
"Action" : [
"s3:GetBucketLocation",
"s3:PutObject",
"s3:GetObject",
"s3:GetEncryptionConfiguration",
"s3:AbortMultipartUpload",
"s3:ListMultipartUploadParts",
"s3:ListBucket",
"s3:ListBucketMultipartUploads"
],
"Resource" : "*"
}
```
Additionally, this policy is deprecated by AWS:
> This policy will soon be deprecated. Please use AmazonSSMManagedInstanceCore policy to enable AWS Systems Manager service core functionality on EC2 instances. For more information see https://docs.aws.amazon.com/systems-manager/latest/userguide/setup-instance-pr …

fix: replace AmazonEC2RoleforSSM with AmazonSSMManagedInstanceCore managed policy

---

package-lock.json
package.json
packer/linux/ubuntu-focal.pkr.hcl
packer/macos/macos.pkr.hcl
packer/windows/windows.pkr.hcl

Building agent images fails when using terraform provider amazon v1.3.10 due to [a missing checksum file](https://semaphore.semaphoreci.com/jobs/4ae4ec48-104e-440b-8f1a-6286e0eab3c4#L365) (packer-plugin-amazon_v1.3.10_SHA256SUMS) on the release page, resulting in a 404 error. Pin to v1.3.9 as a temporary workaround.
See [the related issue](https://github.com/renderedtext/tasks/issues/8459).
Related amazon packer plugin issue: https://github.com/hashicorp/packer-plugin-amazon/issues/586.

fix(packer): pin hashicorp/amazon plugin to 1.3.9 to avoid 404 on v1.3.10
